./analysis/coala
./analysis/flake8
./analysis/line_profiler
./analysis/memory_profiler
./analysis/pep8
./analysis/pycallgraph
./analysis/pylama
./analysis/pylint
./build/dh-virtualenv
./build/nuitka
./build/pybuilder
./build/pyinstaller
./build/pynsist
./document/mkdocs
./document/pdoc
./document/pycco
./document/sphinx
./test/coverage
./test/green
./test/mamba
./test/nose
./test/nose2
./test/pytest
./test/tox
./test/unittest